<?php

use Dotenv\Dotenv;
use Opekunov\LaravelTelegramBot\Exceptions\TelegramBadTokenException;
use Opekunov\LaravelTelegramBot\Telegram;
use Opekunov\LaravelTelegramBot\TelegramHandler;
use PHPUnit\Framework\TestCase;

class TelegramCoreTests extends TestCase
{
    private Telegram $tg;
    private TelegramHandler $tgHandler;

    /** @test */
    public function badToken()
    {
        $this->expectException(TelegramBadTokenException::class);
        $tg = new Telegram('1234567');
        $tg->getMe();
    }

    /** @test */
    public function getMe()
    {
        $response = $this->tg->getMe();
        $this->assertIsArray($response);
    }

    /** @test */
    public function getUpdates()
    {
        $res = $this->tgHandler->getUpdates();

        $this->assertIsArray($res);
        $this->assertArrayHasKey('update_id', $res[0]);
    }

    protected function setUp(): void
    {
        $env = Dotenv::createImmutable(__DIR__.'/../');
        $env->load();
        $this->tg = new Telegram($_ENV['TELEGRAM_BOT_TOKEN']);
        $this->tgHandler = new TelegramHandler($_ENV['TELEGRAM_BOT_TOKEN']);
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
